import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 
  'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 
  'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 
  'Delhi (NCT)', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry'
];

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिंदी' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ' }
];

export const CROPS_LOCALIZED = {
  wheat: { en: 'Wheat', hi: 'गेहूं', mr: 'गहू', ta: 'கோதுமை', te: 'గోధుమలు', bn: 'গম', gu: 'ઘઉં', kn: 'ಗೋಧಿ', ml: 'ഗോതമ്പ്', pa: 'ਕਣਕ', or: 'ଗହମ' },
  rice: { en: 'Rice / Paddy', hi: 'धान / चावल', mr: 'तांदूळ / भात', ta: 'நெல்', te: 'వరి / బియ్యం', bn: 'ধান / চাল', gu: 'ડાંગર / ચોખા', kn: 'ಬತ್ತ / ಅಕ್ಕಿ', ml: 'നെല്ല് / അരി', pa: 'ਝੋਨਾ / ਚੌਲ', or: 'ଧାନ / ଚାଉଳ' },
  tomato: { en: 'Tomato', hi: 'टमाटर', mr: 'टोमॅटो', ta: 'தக்காளி', te: 'టమాటా', bn: 'টমেটো', gu: 'ટામેટા', kn: 'ಟೊಮೆಟೊ', ml: 'തക്കാളി', pa: 'ਟਮਾਟਰ', or: 'ଟମାଟୋ' },
  cotton: { en: 'Cotton', hi: 'कपास', mr: 'कापूस', ta: 'பருத்தி', te: 'ప్రత్తి', bn: 'তুলা', gu: 'કપાસ', kn: 'ಹತ್ತಿ', ml: 'പരുത്തി', pa: 'ਕਪਾਹ', or: '<ctrl42>କପା' },
  sugarcane: { en: 'Sugarcane', hi: 'गन्ना', mr: 'ऊस', ta: 'கரும்பு', te: 'చెరకు', bn: 'আখ', gu: 'શેરડી', kn: 'ಕಬ್ಬು', ml: 'കരിമ്പ്', pa: 'ਗੰਨਾ', or: 'ଆଖୁ' },
  maize: { en: 'Maize (Corn)', hi: 'मक्का', mr: 'मका', ta: 'சோளம்', te: 'మొక్కజొన్న', bn: 'ভুট্টা', gu: 'મકાઈ', kn: 'ಮೆಕ್ಕೆಜೋಳ', ml: 'ചോളം', pa: 'ਮੱਕੀ', or: 'ମକା' },
  potato: { en: 'Potato', hi: 'आलू', mr: 'बटाटा', ta: 'உருளைக்கிழங்கு', te: 'బంగాళాదుంప', bn: 'আলু', gu: 'બટાકા', kn: 'ಆಲೂಗಡ್ಡೆ', ml: 'ഉരുളക്കിഴങ്ങ്', pa: 'ਆਲੂ', or: 'ଆଳୁ' },
  soybean: { en: 'Soybean', hi: 'सोयाबीन', mr: 'सोयाबीन', ta: 'சோயாபீன்', te: 'సోయాబీన్', bn: 'সয়াবিন', gu: 'સોયાબીન', kn: 'ಸೋಯಾಬீன்', ml: 'സോയാബീൻ', pa: 'ਸੋਇਆਬੀਨ', or: 'ସୋୟାବିନ୍' },
  mustard: { en: 'Mustard', hi: 'सरसों', mr: 'मोहरी', ta: 'கடுகு', te: 'ఆవాలు', bn: 'সরিষা', gu: 'રાઈ / સરસવ', kn: 'ಸಾಸಿವೆ', ml: 'കടുക്', pa: 'ਸਰ੍ਹੋਂ', or: 'ସୋରିଷ' },
  chana: { en: 'Gram / Chana', hi: 'चना', mr: 'हरभरा', ta: 'கொண்டைக்கடலை', te: 'శనగలు', bn: 'ছোলা', gu: 'ચણા', kn: 'ಕಡಲೆ', ml: 'കടല', pa: 'ਛੋਲੇ', or: 'ବୁଟ' },
  groundnut: { en: 'Groundnut / Peanut', hi: 'मूंगफली', mr: 'भुईमूग', ta: 'நிலக்கடலை', te: 'వేరుశనగ', bn: 'চীনাবাদাম', gu: 'મગફળી', kn: 'ಕಡಲೆಕಾಯಿ', ml: 'നിലക്കടല', pa: 'ਮੂੰਗਫਲੀ', or: 'ଚିନାବାଦାମ' },
  onion: { en: 'Onion', hi: 'प्याज', mr: 'कांदा', ta: 'வெங்காயம்', te: 'ఉల్లిపాయ', bn: 'পেঁয়াজ', gu: 'ડુંગળી', kn: 'ಈರುಳ್ಳಿ', ml: 'സവാള', pa: 'ਪਿਆਜ਼', or: 'ପିଆଜ' },
  chili: { en: 'Chili / Green Pepper', hi: 'मिर्च', mr: 'मिरची', ta: 'மிளகாய்', te: 'మిరపకాయ', bn: 'মরিচ', gu: 'મરચું', kn: 'ಮೆಣಸಿನಕಾಯಿ', ml: 'മുളക്', pa: 'ਮਿਰਚ', or: 'ଲଙ୍କା' },
  apple: { en: 'Apple', hi: 'सेब', mr: 'सफरचंद', ta: 'ஆப்பிள்', te: 'యాపిల్', bn: 'আপেল', gu: 'સફરજન', kn: 'ಸೇಬು', ml: 'ആപ്പിൾ', pa: 'ਸੇਬ', or: 'ସେଓ' },
  mango: { en: 'Mango', hi: 'आम', mr: 'आंबा', ta: 'மாம்பழம்', te: 'మామిడి', bn: 'আম', gu: 'કેરી', kn: 'ಮಾವಿನಹಣ್ಣು', ml: 'മാമ്പഴം', pa: 'ਅੰਬ', or: 'ଆମ୍ବ' },
  banana: { en: 'Banana', hi: 'केला', mr: 'केळी', ta: 'வாழைப்பழம்', te: 'అరటి', bn: 'কলা', gu: 'કેળાં', kn: 'ಬಾಳೆಹಣ್ಣು', ml: 'വാഴപ്പഴം', pa: 'ਕੇਲਾ', or: 'କਦଳୀ' },
  citrus: { en: 'Citrus / Orange', hi: 'संतरा / नींबू', mr: 'संत्री / लिंबू', ta: 'எலுமிச்சை', te: 'నిమ్మకాయ', bn: 'লেবু', gu: 'સંતરા / લીંબુ', kn: 'ಕಿತ್ತಳೆ', ml: 'ഓറഞ്ച് / ചെറുനാരങ്ങ', pa: 'সংਤਰਾ', or: 'ଲେମ୍ବୁ' },
  turmeric: { en: 'Turmeric', hi: 'हल्दी', mr: 'हळद', ta: 'மஞ்சள்', te: 'పసుపు', bn: 'হলুদ', gu: 'હળદર', kn: 'ಅರಿಶಿನ', ml: 'മഞ്ഞൾ', pa: 'ਹਲਦੀ', or: 'ହଳଦୀ' },
  tea: { en: 'Tea', hi: 'चाय', mr: 'हाताचा चहा', ta: 'தேயிலை', te: 'తేయాకు', bn: 'চা', gu: 'ચા', kn: 'ಟೀ', ml: 'തേയില', pa: 'ਚਾਹ', or: 'ଚା' },
  coffee: { en: 'Coffee', hi: 'कॉफी', mr: 'कॉफी', ta: 'காபி', te: 'కాఫీ', bn: 'কফি', gu: 'કોફી', kn: 'ಕಾಫಿ', ml: 'കാപ്പി', pa: 'ਕੌਫ਼ੀ', or: 'କଫି' },
  jute: { en: 'Jute', hi: 'जूट / पटसन', mr: 'ताग', ta: 'சணல்', te: 'జనపనార', bn: 'পাট', gu: 'શણ', kn: 'ಶಣಬು', ml: 'ചണം', pa: 'ਪਟਸਨ', or: 'ଝୋଟ' },
  barley: { en: 'Barley', hi: 'जौ', mr: 'सातू', ta: 'பார்லி', te: 'బార్లీ', bn: 'বার্লি', gu: 'જવ', kn: 'ಬಾರ್ಲಿ', ml: 'ബാർലി', pa: 'ਜੌਂ', or: 'ଜବ' },
  bajra: { en: 'Bajra / Pearl Millet', hi: 'बाजरा', mr: 'बाजरी', ta: 'கம்பு', te: 'సజ్జలు', bn: 'বাজরা', gu: 'બાજરી', kn: 'ಸಜ್ಜೆ', ml: 'കമ്പ്', pa: 'ਬਾਜਰਾ', or: 'ବାଜରା' },
  jowar: { en: 'Jowar / Sorghum', hi: 'ज्वार', mr: 'ज्वारी', ta: 'சோளம்', te: 'జొన్నలు', bn: 'জোয়ার', gu: 'જુવાર', kn: 'ಜೋಳ', ml: 'ചോളം', pa: 'ਜੁਆਰ', or: 'ଜୁଆର' },
  ragi: { en: 'Ragi / Finger Millet', hi: 'रागी / मडुआ', mr: 'नाचणी / नाचनी', ta: 'கேழ்வரகு / ராகி', te: 'రాగులు', bn: 'রাগি', gu: 'રાગી', kn: 'ರಾಗಿ', ml: 'റാഗി', pa: 'ਰਾਗੀ', or: 'ମାଣ୍ଡିଆ' }
};

export const translations = {
  en: {
    brandName: 'KisanAI',
    dashboard: 'Dashboard',
    cropRec: 'Crop Recommendation',
    diseaseDetect: 'Disease Detection',
    advisory: 'AI Advisory',
    schemes: 'Govt Schemes',
    welcomeFarmer: 'Welcome back, Farmer!',
    weatherOverview: 'Live Weather Overview',
    soilType: 'Soil Type',
    farmSize: 'Farm Size (Acres)',
    location: 'Location / State',
    getRecommendation: 'Get Recommendations',
    analyzePlant: 'Analyze Plant Leaf',
    generateAdvisory: 'Generate AI Advisory',
    matchGovtSchemes: 'Check Eligible Schemes',
    logout: 'Logout',
    login: 'Login',
    signup: 'Sign Up',
    quickTools: 'Quick Farm Tools',
    aiMatching: 'AI Matching',
    instantScanner: 'Instant Scanner',
    bilingualTag: 'Multilingual AI',
    subsidiesTag: '₹ Subsidies',
    cropRecDesc: 'Calculate soil NPK, pH, and climate parameters to discover top high-yielding crops with market pricing.',
    diseaseDesc: 'Upload crop leaf photo to diagnose diseases, organic/chemical treatment steps, and nearby pesticide Mandis.',
    advisoryDesc: 'Get customized daily action advice on irrigation schedules, fertilizer doses, and weather risk warnings.',
    schemesDesc: 'Check eligibility for PM-Kisan, Fasal Bima Yojana, Kisan Credit Card, and SMAM subsidies based on land size.',
    selectState: 'Select Indian State / UT',
    annualIncome: 'Annual Family Income (₹)',
    calculateBtn: 'Calculate Optimal Crops',
    scanningBtn: 'AI Analyzing Leaf Scan...',
    recalculateBtn: 'Recalculate Eligible Schemes',
    eligible: 'Eligible',
    notEligible: 'Not Eligible',
    reqDocs: 'Required Documents',
    applyPortal: 'Apply via Official Portal',
    
    // Disease Detection Specific
    selectUploadTitle: 'Select Crop & Upload Plant Leaf Photo',
    targetCrop: 'Target Crop',
    clickDropBox: 'Click to Choose Photo or Drag & Drop Leaf Image Here',
    supportsText: 'Supports JPG, PNG, WEBP (Max 10MB)',
    changePhoto: 'Change Photo',
    removePhoto: 'Remove Photo',
    scanDiagnoseBtn: 'Scan & Diagnose Disease',
    scientificName: 'Scientific Binomial',
    aiConfidence: 'AI Confidence Score',
    severityLevel: 'Severity Level',
    symptomsTitle: 'Observed Leaf Symptoms & Infection Stage',
    organicRemedy: 'Organic & Bio-Fungicide Remedy',
    chemicalRemedy: 'Recommended Chemical Control & Spray Protocol',
    preventiveCare: 'Preventive Cultural Practices',
    nearbyMandisTitle: 'Nearby Pesticide Mandis & Outlets',
    awaitingInput: 'Awaiting Leaf Photo Input',
    awaitingDesc: 'Click the upload box above to attach a crop leaf photo for instant AI diagnosis and YouTube solution video.',
    
    // Video & Google Search Section
    googleKnowledgeBanner: 'Search Disease & ICAR Guidelines from Google Knowledge Base',
    googleSearchBtn: 'Google Search',
    youtubeVideoHeader: 'YouTube Solution Video Tutorial',
    watchVideoBtn: 'Watch Treatment Video on YouTube'
  },
  hi: {
    brandName: 'किसान-एआई',
    dashboard: 'डैशबोर्ड',
    cropRec: 'फसल सिफारिश',
    diseaseDetect: 'रोग पहचान',
    advisory: 'एआई कृषि सलाह',
    schemes: 'सरकारी योजनाएं',
    welcomeFarmer: 'स्वागत है, किसान मित्र!',
    weatherOverview: 'लाइव मौसम पूर्वानुमान',
    soilType: 'मिट्टी का प्रकार',
    farmSize: 'खेत का आकार (एकड़)',
    location: 'स्थान / राज्य',
    getRecommendation: 'फसल सिफारिश प्राप्त करें',
    analyzePlant: 'पौधे की पत्ती जांचें',
    generateAdvisory: 'एआई सलाह प्राप्त करें',
    matchGovtSchemes: 'पात्र योजनाएं देखें',
    logout: 'लॉगआउट',
    login: 'लॉगिन',
    signup: 'साइन अप',
    quickTools: 'त्वरित कृषि उपकरण',
    aiMatching: 'एआई मिलान',
    instantScanner: 'त्वरित स्कैनर',
    bilingualTag: 'बहुभाषी एआई',
    subsidiesTag: '₹ सब्सिडी',
    cropRecDesc: 'बाजार मूल्य निर्धारण के साथ उच्च उपज वाली फसलों की खोज के लिए मिट्टी NPK, pH और जलवायु मापदंडों की गणना करें।',
    diseaseDesc: 'रोगों, जैविक/रासायनिक उपचार चरणों और नजदीकी कीटनाशक मंडियों का निदान करने के लिए फसल पत्ती की फोटो अपलोड करें।',
    advisoryDesc: 'सिंचाई कार्यक्रम, उर्वरक खुराक और मौसम जोखिम चेतावनी पर अनुकूलित दैनिक कार्रवाई सलाह प्राप्त करें।',
    schemesDesc: 'भूमि के आकार के आधार पर पीएम-किसान, फसल बीमा योजना, किसान क्रेडिट कार्ड और एसएमएएम सब्सिडी की पात्रता जांचें।',
    selectState: 'भारतीय राज्य / केंद्र शासित प्रदेश चुनें',
    annualIncome: 'वार्षिक पारिवारिक आय (₹)',
    calculateBtn: 'सर्वश्रेष्ठ फसलें खोजें',
    scanningBtn: 'एआई पत्ती स्कैन का विश्लेषण जारी है...',
    recalculateBtn: 'पात्र योजनाओं की पुनर्गणना करें',
    eligible: 'पात्र',
    notEligible: 'अपात्र',
    reqDocs: 'आवश्यक दस्तावेज',
    applyPortal: 'आधिकारिक पोर्टल पर आवेदन करें',

    selectUploadTitle: 'फसल चुनें और पत्ती की फोटो अपलोड करें',
    targetCrop: 'लक्ष्य फसल',
    clickDropBox: 'फोटो चुनने के लिए क्लिक करें या यहाँ पत्ती की फोटो खींचकर छोड़ें',
    supportsText: 'JPG, PNG, WEBP समर्थित (अधिकतम 10MB)',
    changePhoto: 'फोटो बदलें',
    removePhoto: 'फोटो हटाएं',
    scanDiagnoseBtn: 'रोग का स्कैन और निदान करें',
    scientificName: 'वैज्ञानिक नाम',
    aiConfidence: 'एआई विश्वसनीयता स्कोर',
    severityLevel: 'गंभीरता का स्तर',
    symptomsTitle: 'देखे गए लक्षण एवं संक्रमण चरण',
    organicRemedy: 'जैविक एवं बायोकंट्रोल उपचार',
    chemicalRemedy: 'अनुशंसित रासायनिक नियंत्रण एवं छिड़काव',
    preventiveCare: 'निवारक कृषि प्रबंधन',
    nearbyMandisTitle: 'नजदीकी कीटनाशक मंडियां एवं विक्रेता',
    awaitingInput: 'पत्ती की फोटो की प्रतीक्षा है',
    awaitingDesc: 'त्वरित एआई निदान और यूट्यूब समाधान वीडियो के लिए ऊपर फोटो अपलोड बॉक्स पर क्लिक करके फोटो संलग्न करें।',

    googleKnowledgeBanner: 'गूगल नॉलेज बेस से रोग एवं आईसीएआर दिशानिर्देश खोजें',
    googleSearchBtn: 'गूगल सर्च पर जानकारी देखें',
    youtubeVideoHeader: 'यूट्यूब समाधान वीडियो ट्यूटोरियल',
    watchVideoBtn: 'यूट्यूब पर उपचार वीडियो देखें'
  },
  mr: {
    brandName: 'किसान-एआय',
    dashboard: 'डॅशबोर्ड',
    cropRec: 'पिक शिफारस',
    diseaseDetect: 'रोग निदान',
    advisory: 'एआय कृषी सल्ला',
    schemes: 'शासकीय योजना',
    welcomeFarmer: 'जीवो शेतकरी! स्वागत आहे!',
    weatherOverview: 'थेट हवामान अंदाज',
    soilType: 'मातीचा प्रकार',
    farmSize: 'शेताचे क्षेत्रफळ (एकर)',
    location: 'स्थान / राज्य',
    getRecommendation: 'पिक शिफारस मिळवा',
    analyzePlant: 'पानाची पाहणी करा',
    generateAdvisory: 'सल्ला मिळवा',
    matchGovtSchemes: 'पात्र योजना तपासा',
    logout: 'बाहेर पडा',
    login: 'लॉगिन',
    signup: 'साइन अप',
    quickTools: 'जलद शेती साधने',
    aiMatching: 'एआय मॅचिंग',
    instantScanner: 'इन्स्टंट स्कॅनर',
    bilingualTag: 'बहुभाषिक एआय',
    subsidiesTag: '₹ अनुदान',
    cropRecDesc: 'जास्त उत्पन्न देणाऱ्या पिकांचा शोध घेण्यासाठी मातीची NPK, pH आणि हवामान घटकांची गणना करा.',
    diseaseDesc: 'रोगाचे निदान, सेंद्रिय/रासायनिक उपचार आणि जवळील कृषी केंद्रांची माहिती मिळवण्यासाठी पानाचा फोटो अपलोड करा.',
    advisoryDesc: 'सिंचन वेळापत्रक, खतांची मात्रा आणि हवामान धोक्याच्या इशारे यावर दररोज सानुकूलित सल्ला मिळवा.',
    schemesDesc: 'पीएम-किसान, पीक विमा, किसान क्रेडिट कार्ड आणि कृषी यांत्रिकीकरण योजनेसाठी पात्रता तपासा.',
    selectState: 'राज्य / केंद्रशासित प्रदेश निवडा',
    annualIncome: 'वार्षिक कौटुंबिक उत्पन्न (₹)',
    calculateBtn: 'उत्कृष्ट पिके शोधा',
    scanningBtn: 'पानाचे स्कॅनिंग सुरू आहे...',
    recalculateBtn: 'योजनांची पुन्हा तपासणी करा',
    eligible: 'पात्र',
    notEligible: 'अपात्र',
    reqDocs: 'आवश्यक कागदपत्रे',
    applyPortal: 'अधिकृत पोर्टलवर अर्ज करा',

    selectUploadTitle: 'पिक निवडा आणि पानाचा फोटो अपलोड करा',
    targetCrop: 'पिक निवडा',
    clickDropBox: 'फोटो निवडण्यासाठी क्लिक करा किंवा येथे पानाचा फोटो टाका',
    supportsText: 'JPG, PNG, WEBP समर्थित (कमाल 10MB)',
    changePhoto: 'फोटो बदला',
    removePhoto: 'फोटो काढा',
    scanDiagnoseBtn: 'स्कॅन करा आणि रोग निदान करा',
    scientificName: 'शास्त्रीय नाव',
    aiConfidence: 'एआय अचूकता प्रमाण',
    severityLevel: 'तीव्रता पातळी',
    symptomsTitle: 'आढळलेली लक्षणे आणि रोगाची पायरी',
    organicRemedy: 'सेंद्रिय आणि जैविक उपचार',
    chemicalRemedy: 'रासायनिक फवारणी आणि नियंत्रण',
    preventiveCare: 'प्रतिबंधात्मक काळजी',
    nearbyMandisTitle: 'जवळील कृषी सेवा केंद्र व बाजार समित्या',
    awaitingInput: 'पानाच्या फोटोची वाट पाहत आहे',
    awaitingDesc: 'रोग निदानासाठी वर फोटो अपलोड करा.',

    googleKnowledgeBanner: 'गूगल नॉलेज बेसवरून माहिती व मार्गदर्शक सूचना शोधा',
    googleSearchBtn: 'गूगल सर्चवर माहिती पहा',
    youtubeVideoHeader: 'यूट्यूब उपाय व्हिडिओ मार्गदर्शन',
    watchVideoBtn: 'यूट्यूबवर उपाय व्हिडिओ पहा'
  },
  ta: {
    brandName: 'கிசான்-AI',
    dashboard: 'டாஷ்போர்டு',
    cropRec: 'பயிர் பரிந்துரை',
    diseaseDetect: 'நோய் கண்டறிதல்',
    advisory: 'AI விவசாய ஆலோசனை',
    schemes: 'அரசு திட்டங்கள்',
    welcomeFarmer: 'வணக்கம், விவசாயி சகோதரரே!',
    weatherOverview: 'நேரலை வானிலை முன்னறிவிப்பு',
    soilType: 'மண் வகை',
    farmSize: 'நில அளவு (ஏக்கர்)',
    location: 'இடம் / மாநிலம்',
    getRecommendation: 'பரிந்துரை பெறுக',
    analyzePlant: 'இலையை பரிசோதிக்கவும்',
    generateAdvisory: 'ஆலோசனை பெறுக',
    matchGovtSchemes: 'தகுதியான திட்டங்கள்',
    logout: 'வெளியேறு',
    login: 'உள்நுழைவு',
    signup: 'பதிவு செய்ய',
    quickTools: 'விரைவு விவசாய கருவிகள்',
    aiMatching: 'AI பொருத்தம்',
    instantScanner: 'உடனடி ஸ்கேனர்',
    bilingualTag: 'பன்மொழி AI',
    subsidiesTag: '₹ மானியங்கள்',
    cropRecDesc: 'அதிக மகசூல் தரும் பயிர்களைக் கண்டறிய மண் NPK, pH மற்றும் காலநிலையைக் கணக்கிடுங்கள்.',
    diseaseDesc: 'பயிர் நோய்கள் மற்றும் இயற்கை/இரசாயன தீர்வுகளை அறிய இலை புகைப்படத்தைப் பதிவேற்றவும்.',
    advisoryDesc: 'நீர்ப்பாசனம் மற்றும் உர அட்டவணை பற்றிய தினசரி AI ஆலோசனையைப் பெறுங்கள்.',
    schemesDesc: 'பிஎம்-கிசான், பயிர் காப்பீடு மற்றும் கிசான் கிரெடிட் கார்டு தகுதியைச் சரிபார்க்கவும்.',
    selectState: 'மாநிலம் / யூனியன் பிரதேசம் தேர்ந்தெடுக்கவும்',
    annualIncome: 'ஆண்டு வருமானம் (₹)',
    calculateBtn: 'சிறந்த பயிர்களைக் கண்டறியவும்',
    scanningBtn: 'ஆய்வு செய்யப்படுகிறது...',
    recalculateBtn: 'மீண்டும் சரிபார்க்கவும்',
    eligible: 'தகுதியானது',
    notEligible: 'தகுதியில்லை',
    reqDocs: 'தேவையான ஆவணங்கள்',
    applyPortal: 'அதிகாரப்பூர்வ இணையதளத்தில் விண்ணப்பிக்கவும்',

    selectUploadTitle: 'பயிரைத் தேர்ந்தெடுத்து புகைப்படத்தைப் பதிவேற்றவும்',
    targetCrop: 'பயிர் தேர்வு',
    clickDropBox: 'புகைப்படத்தைத் தேர்ந்தெடுக்க இங்கே கிளிக் செய்யவும்',
    supportsText: 'JPG, PNG, WEBP ஆதரவு (அதிகபட்சம் 10MB)',
    changePhoto: 'புகைப்படத்தை மாற்றவும்',
    removePhoto: 'புகைப்படத்தை நீக்கவும்',
    scanDiagnoseBtn: 'ஸ்கேன் செய்து நோயைக் கண்டறியவும்',
    scientificName: 'அறிவியல் பெயர்',
    aiConfidence: 'AI துல்லிய வீதம்',
    severityLevel: 'பாதிப்பு அளவு',
    symptomsTitle: 'கண்டறியப்பட்ட அறிகுறிகள்',
    organicRemedy: 'இயற்கை மற்றும் உயிரியல் சிகிச்சை',
    chemicalRemedy: 'இரசாயன தெளிப்பு முறை',
    preventiveCare: 'முன்னெச்சரிக்கை முறைகள்',
    nearbyMandisTitle: 'அருகிலுள்ள மருந்து விற்பனை நிலையங்கள்',
    awaitingInput: 'இலை புகைப்படத்திற்காக காத்திருக்கிறது',
    awaitingDesc: 'நோயைக் கண்டறிய புகைப்படத்தைப் பதிவேற்றவும்.',

    googleKnowledgeBanner: 'கூகிள் அறிவுக் களஞ்சியத்தில் விவரங்களைத் தேடுங்கள்',
    googleSearchBtn: 'கூகிள் தேடலில் பார்க்கவும்',
    youtubeVideoHeader: 'யூடியூப் தீர்வு வீடியோ பயிற்சி',
    watchVideoBtn: 'யூடியூப்பில் சிகிச்சை வீடியோவைப் பார்க்கவும்'
  },
  te: {
    brandName: 'కిసాన్-AI',
    dashboard: 'డాష్‌బోర్డ్',
    cropRec: 'పంట సిఫార్సు',
    diseaseDetect: 'వ్యాధి గుర్తింపు',
    advisory: 'AI వ్యవసాయ సలహా',
    schemes: 'ప్రభుత్వ పథకాలు',
    welcomeFarmer: 'స్వాగతం, రైతు మిత్రమా!',
    weatherOverview: 'లైవ్ వాతావరణ సమాచారం',
    soilType: 'నేల రకం',
    farmSize: 'పొలం పరిమాణం (ఎకరాలు)',
    location: 'ప్రాంతం / రాష్ట్రం',
    getRecommendation: 'సిఫార్సు పొందండి',
    analyzePlant: 'ఆకును పరీక్షించండి',
    generateAdvisory: 'సలహా పొందండి',
    matchGovtSchemes: 'అర్హత ఉన్న పథకాలు',
    logout: 'లాగ్ అవుట్',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    quickTools: 'త్వరిత వ్యవసాయ సాధనాలు',
    aiMatching: 'AI మ్యాచింగ్',
    instantScanner: 'ఇన్‌స్టంట్ స్కేనర్',
    bilingualTag: 'బహుభాషా AI',
    subsidiesTag: '₹ సబ్సిడీలు',
    cropRecDesc: 'ఎక్కువ దిగుబడి ఇచ్చే పంటలను కనుగొనడానికి నేల NPK, pH మరియు వాతావరణాన్ని లెక్కించండి.',
    diseaseDesc: 'పంట తెగుళ్లు మరియు సేంద్రీయ/రసాయన నివారణ చర్యల కోసం ఆకు ఫోటోను అప్‌లోడ్ చేయండి.',
    advisoryDesc: 'నీటి పారుదల మరియు ఎరువుల మోతాదుపై ప్రతిరోజూ AI సలహాలను పొందండి.',
    schemesDesc: 'పీఎం-కిసాన్, ఫసల్ బీమా మరియు కేసీసీ పథకాల అర్హతను తనిఖీ చేయండి.',
    selectState: 'రాష్ట్రం / కేంద్రపాలిత ప్రాంతం ఎంచుకోండి',
    annualIncome: 'వార్షిక కుటుంబ ఆదాయం (₹)',
    calculateBtn: 'ఉత్తమ పంటలను కనుగొనండి',
    scanningBtn: 'పరీక్షిస్తోంది...',
    recalculateBtn: 'మళ్లీ తనిఖీ చేయండి',
    eligible: 'అర్హత ఉంది',
    notEligible: 'అర్హత లేదు',
    reqDocs: 'కావలసిన పత్రాలు',
    applyPortal: 'అధికారిక పోర్టల్‌లో దరఖాస్తు చేసుకోండి',

    selectUploadTitle: 'పంటను ఎంచుకోండి మరియు ఫోటోను అప్‌లోడ్ చేయండి',
    targetCrop: 'పంట ఎంపిక',
    clickDropBox: 'ఫోటో ఎంచుకోవడానికి ఇక్కడ క్లిక్ చేయండి',
    supportsText: 'JPG, PNG, WEBP మద్దతు ఇస్తుంది (గరిష్టంగా 10MB)',
    changePhoto: 'ఫోటో మార్చండి',
    removePhoto: 'ఫోటో తొలగించండి',
    scanDiagnoseBtn: 'వ్యాధిని స్కాన్ చేసి గుర్తించండి',
    scientificName: 'శాస్త్రీయ నామం',
    aiConfidence: 'AI ఖచ్చితత్వ శాతం',
    severityLevel: 'తీవ్రత స్థాయి',
    symptomsTitle: 'గుర్తించిన లక్షణాలు',
    organicRemedy: 'సేంద్రీయ నివారణ చర్యలు',
    chemicalRemedy: 'రసాయన పిచికారీ వివరాలు',
    preventiveCare: 'ముందస్తు జాగ్రత్తలు',
    nearbyMandisTitle: 'సమీప వ్యవసాయ విక్రయ కేంద్రాలు',
    awaitingInput: 'ఆకు ఫోటో కోసం వేచి చూస్తోంది',
    awaitingDesc: 'తెగుళ్లను గుర్తించడానికి ఆకు ఫోటోను అప్‌లోడ్ చేయండి.',

    googleKnowledgeBanner: 'గూగుల్ నాలెడ్జ్ బేస్ నుండి నివారణ సమాచారం చూడండి',
    googleSearchBtn: 'గూగుల్ సెర్చ్‌లో చూడండి',
    youtubeVideoHeader: 'యూట్యూబ్ నివారణ వీడియో గైడ్',
    watchVideoBtn: 'యూట్యూబ్‌లో నివారణ వీడియో చూడండి'
  },
  bn: {
    brandName: 'কিসান-AI',
    dashboard: 'ড্যাশবোর্ড',
    cropRec: 'ফসল সুপারিশ',
    diseaseDetect: 'রোগ শনাক্তকরণ',
    advisory: 'AI কৃষি পরামর্শ',
    schemes: 'সরকারি প্রকল্প',
    welcomeFarmer: 'স্বাগতম, কৃষক বন্ধু!',
    weatherOverview: 'লাইভ আবহাওয়া পূর্বাভাস',
    soilType: 'মাটির ধরণ',
    farmSize: 'জমির পরিমাণ (একর)',
    location: 'স্থান / রাজ্য',
    getRecommendation: 'সুপারিশ পান',
    analyzePlant: 'পাতা পরীক্ষা করুন',
    generateAdvisory: 'পরামর্শ গ্রহণ করুন',
    matchGovtSchemes: 'যোগ্য প্রকল্প দেখুন',
    logout: 'লগআউট',
    login: 'লগইন',
    signup: 'সাইন আপ',
    quickTools: 'দ্রুত কৃষি সরঞ্জাম',
    aiMatching: 'AI ম্যাচিং',
    instantScanner: 'ইনস্ট্যান্ট স্ক্যানার',
    bilingualTag: 'বহুভাষিক AI',
    subsidiesTag: '₹ সরকারি ভরতুকি',
    cropRecDesc: 'উচ্চ ফলনশীল ফসলের জন্য মাটির NPK, pH এবং আবহাওয়া বিশ্লেষণ করুন।',
    diseaseDesc: 'রোগ শনাক্তকরণ এবং জৈব ও রাসায়নিক প্রতিকারের জন্য পাতার ছবি আপলোড করুন।',
    advisoryDesc: 'সেচ সময়সূচী এবং সার প্রয়োগের দৈনিক AI পরামর্শ পান।',
    schemesDesc: 'পিএম-কিসান, ফসল বিমা এবং কেসিসি প্রকল্পের যোগ্যতা পরীক্ষা করুন।',
    selectState: 'রাজ্য / কেন্দ্রশাসিত অঞ্চল নির্বাচন করুন',
    annualIncome: 'বার্ষিক পারিবারিক আয় (₹)',
    calculateBtn: 'সেরা ফসল খুঁজুন',
    scanningBtn: 'স্ক্যান করা হচ্ছে...',
    recalculateBtn: 'পুনরায় পরীক্ষা করুন',
    eligible: 'যোগ্য',
    notEligible: 'যোগ্য নন',
    reqDocs: 'প্রয়োজনীয় নথি',
    applyPortal: 'অফিসিয়াল পোর্টালে আবেদন করুন',

    selectUploadTitle: 'ফসল নির্বাচন করুন এবং পাতার ছবি আপলোড করুন',
    targetCrop: 'ফসল নির্বাচন',
    clickDropBox: 'ছবি নির্বাচন করতে এখানে ক্লিক করুন',
    supportsText: 'JPG, PNG, WEBP সমর্থিত (সর্বোচ্চ 10MB)',
    changePhoto: 'ছবি পরিবর্তন করুন',
    removePhoto: 'ছবি মুছুন',
    scanDiagnoseBtn: 'রোগ স্ক্যান ও নির্ণয় করুন',
    scientificName: 'বৈজ্ঞানিক নাম',
    aiConfidence: 'AI নির্ভুলতার হার',
    severityLevel: 'তীব্রতার মাত্রা',
    symptomsTitle: 'দেখা যাওয়া লক্ষণসমূহ',
    organicRemedy: 'জৈব প্রতিকার',
    chemicalRemedy: 'রাসায়নিক স্প্রে পদ্ধতি',
    preventiveCare: 'প্রতিরোধমূলক ব্যবস্থা',
    nearbyMandisTitle: 'নিকটস্থ কৃষি কেন্দ্র',
    awaitingInput: 'পাতার ছবির জন্য অপেক্ষা করা হচ্ছে',
    awaitingDesc: 'রোগ নির্ণয়ের জন্য ছবি আপলোড করুন।',

    googleKnowledgeBanner: 'গুগল নলেজ বেস থেকে তথ্য অনুসন্ধান করুন',
    googleSearchBtn: 'গুগল সার্চে তথ্য দেখুন',
    youtubeVideoHeader: 'ইউটিউব সমাধান ভিডিও নির্দেশিকা',
    watchVideoBtn: 'ইউটিউবে প্রতিকার ভিডিও দেখুন'
  },
  gu: {
    brandName: 'કિસાન-AI',
    dashboard: 'ડેશબોર્ડ',
    cropRec: 'પાક ભલામણ',
    diseaseDetect: 'રોગ નિદાન',
    advisory: 'AI કૃષિ સલાહ',
    schemes: 'સરકારી યોજનાઓ',
    welcomeFarmer: 'સ્વાગત છે, ખેડૂત મિત્ર!',
    weatherOverview: 'લાઈવ હવામાન પૂર્વાનુમાન',
    soilType: 'જમીનનો પ્રકાર',
    farmSize: 'જમીનનું ક્ષેત્રફળ (એકર)',
    location: 'સ્થળ / રાજ્ય',
    getRecommendation: 'પાક ભલામણ મેળવો',
    analyzePlant: 'પાનની તપાસ કરો',
    generateAdvisory: 'સલાહ મેળવો',
    matchGovtSchemes: 'પાત્ર યોજનાઓ જુઓ',
    logout: 'લોગ આઉટ',
    login: 'લોગિન',
    signup: 'સાઇન અપ',
    quickTools: 'ઝડપી કૃષિ સાધનો',
    aiMatching: 'AI મેચિંગ',
    instantScanner: 'ઇન્સ્ટન્ટ સ્કેનર',
    bilingualTag: 'બહુભાષી AI',
    subsidiesTag: '₹ સબસિડી',
    cropRecDesc: 'વધુ ઉત્પાદન આપતા પાકો શોધવા જમીનના NPK, pH અને હવામાનની ગણતરી કરો.',
    diseaseDesc: 'રોગ નિદાન અને જૈવિક/રાસાયણિક ઉપચાર માટે પાનના ફોટો અપલોડ કરો.',
    advisoryDesc: 'સિંચાઈ સમયપત્રક અને ખાતરના ડોઝ પર દરરોજ AI સલાહ મેળવો.',
    schemesDesc: 'પીએમ-કિસાન, પાક વીમા અને કેસીસી યોજના માટે પાત્રતા ચકાસો.',
    selectState: 'રાજ્ય / કેન્દ્રશાસિત પ્રદેશ પસંદ કરો',
    annualIncome: 'વાર્ષિક કૌટુંબિક આવક (₹)',
    calculateBtn: 'શ્રેષ્ઠ પાકો શોધો',
    scanningBtn: 'સ્કેનિંગ ચાલુ છે...',
    recalculateBtn: 'ફરીથી ચકાસો',
    eligible: 'પાત્ર',
    notEligible: 'અપાત્ર',
    reqDocs: 'જરૂરી દસ્તાવેજો',
    applyPortal: 'સત્તાવાર પોર્ટલ પર અરજી કરો',

    selectUploadTitle: 'પાક પસંદ કરો અને પાનનો ફોટો અપલોડ કરો',
    targetCrop: 'પાક પસંદગી',
    clickDropBox: 'ફોટો પસંદ કરવા અહીં ક્લિક કરો',
    supportsText: 'JPG, PNG, WEBP (મહત્તમ 10MB)',
    changePhoto: 'ફોટો બદલો',
    removePhoto: 'ફોટો દૂર કરો',
    scanDiagnoseBtn: 'રોગ સ્કેન અને નિદાન કરો',
    scientificName: 'વૈજ્ઞાનિક નામ',
    aiConfidence: 'AI ચોકસાઈ દર',
    severityLevel: 'ગંભીરતાનું સ્તર',
    symptomsTitle: 'જોવા મળેલા લક્ષણો',
    organicRemedy: 'જૈવિક સારવાર',
    chemicalRemedy: 'રાસાયણિક છંટકાવ પદ્ધતિ',
    preventiveCare: 'પૂર્વસાવચેતી',
    nearbyMandisTitle: 'નજીકના કૃષિ સેવા કેન્દ્રો',
    awaitingInput: 'પાનના ફોટોની રાહ જોવાય છે',
    awaitingDesc: 'રોગ નિદાન માટે ફોટો અપલોડ કરો.',

    googleKnowledgeBanner: 'ગૂગલ નોલેજ બેઝ પરથી માહિતી શોધો',
    googleSearchBtn: 'ગૂગલ સર્ચ પર જુઓ',
    youtubeVideoHeader: 'યુટ્યુબ સોલ્યુશન વિડિઓ',
    watchVideoBtn: 'યુટ્યુબ પર સારવાર વિડિઓ જુઓ'
  },
  kn: {
    brandName: 'ಕಿಸಾನ್-AI',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    cropRec: 'ಬೆಳೆ ಶಿಫಾರಸು',
    diseaseDetect: 'ರೋಗ ಪತ್ತೆ',
    advisory: 'AI ಕೃಷಿ ಸಲಹೆ',
    schemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    welcomeFarmer: 'ಸ್ವಾಗತ, ರೈತ ಮಿತ್ರ!',
    weatherOverview: 'ನೇರ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
    soilType: 'ಮಣ್ಣಿನ ಮಾದರಿ',
    farmSize: 'ಜಮೀನಿನ ಗಾತ್ರ (ಎಕರೆ)',
    location: 'ಸ್ಥಳ / ರಾಜ್ಯ',
    getRecommendation: 'ಶಿಫಾರಸು ಪಡೆಯಿರಿ',
    analyzePlant: 'ಎಲೆಯನ್ನು ಪರೀಕ್ಷಿಸಿ',
    generateAdvisory: 'ಸಲಹೆ ಪಡೆಯಿರಿ',
    matchGovtSchemes: 'ಅರ್ಹ ಯೋಜನೆಗಳು',
    logout: 'ಲಾಗ್‌ಔಟ್',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    quickTools: 'ತ್ವರಿತ ಕೃಷಿ ಉಪಕರಣಗಳು',
    aiMatching: 'AI ಮ್ಯಾಚಿಂಗ್',
    instantScanner: 'ಇನ್‌ಸ್ಟೆಂಟ್ ಸ್ಕ್ಯಾನರ್',
    bilingualTag: 'ಬಹುಭಾಷಾ AI',
    subsidiesTag: '₹ ಸಬ್ಸಿಡಿಗಳು',
    cropRecDesc: 'ಹೆಚ್ಚಿನ ಇಳುವರಿ ನೀಡುವ ಬೆಳೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು ಮಣ್ಣಿನ NPK, pH ಮತ್ತು ಹವಾಮಾನವನ್ನು ಲೆಕ್ಕಹಾಕಿ.',
    diseaseDesc: 'ಬೆಳೆ ರೋಗಗಳು ಮತ್ತು ಜೈವಿಕ/ರಾಸಾಯನಿಕ ಪರಿಹಾರಗಳಿಗಾಗಿ ಎಲೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    advisoryDesc: 'ನೀರಾವರಿ ವೇಳಾಪಟ್ಟಿ ಮತ್ತು ಗೊಬ್ಬರ ಪ್ರಮಾಣದ ಬಗ್ಗೆ ಪ್ರತಿದಿನ AI ಸಲಹೆ ಪಡೆಯಿರಿ.',
    schemesDesc: 'ಪಿಎಂ-ಕಿಸಾನ್, ಫಸಲ್ ಭೀಮಾ ಮತ್ತು ಕೆಸಿಸಿ યોજના ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ.',
    selectState: 'ರಾಜ್ಯ / ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶ ಆಯ್ಕೆಮಾಡಿ',
    annualIncome: 'ವಾರ್ಷಿಕ ಕೌಟುಂಬಿಕ ಆದಾಯ (₹)',
    calculateBtn: 'ಉತ್ತಮ ಬೆಳೆಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ',
    scanningBtn: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    recalculateBtn: 'ಮತ್ತೊಮ್ಮೆ ಪರಿಶೀಲಿಸಿ',
    eligible: 'ಅರ್ಹತೆ ಇದೆ',
    notEligible: 'ಅರ್ಹತೆ ಇಲ್ಲ',
    reqDocs: 'ಅಗತ್ಯ ದಾಖಲೆಗಳು',
    applyPortal: 'ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',

    selectUploadTitle: 'ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ಎಲೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    targetCrop: 'ಬೆಳೆ ಆಯ್ಕೆ',
    clickDropBox: 'ಫೋಟೋ ಆಯ್ಕೆ ಮಾಡಲು ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ',
    supportsText: 'JPG, PNG, WEBP (ಗರಿಷ್ಠ 10MB)',
    changePhoto: 'ಫೋಟೋ ಬದಲಾಯಿಸಿ',
    removePhoto: 'ಫೋಟೋ ತೆಗೆದುಹಾಕಿ',
    scanDiagnoseBtn: 'ರೋಗವನ್ನು ಪತ್ತೆಹಚ್ಚಿ',
    scientificName: 'ವೈಜ್ಞಾನಿಕ ಹೆಸರು',
    aiConfidence: 'AI ನಿಖರತೆ',
    severityLevel: 'ತೀವ್ರತೆಯ ಮಟ್ಟ',
    symptomsTitle: 'ಕಂಡುಬಂದ ಲಕ್ಷಣಗಳು',
    organicRemedy: 'ಸಾವಯವ ಚಿಕಿತ್ಸೆ',
    chemicalRemedy: 'ರಾಸಾಯನಿಕ ಸಿಂಪಡಣೆ',
    preventiveCare: 'ಮುನ್ನೆಚ್ಚರಿಕೆ ಕ್ರಮಗಳು',
    nearbyMandisTitle: 'ಸಮೀಪದ ಕೃಷಿ ಕೇಂದ್ರಗಳು',
    awaitingInput: 'ಎಲೆಯ ಫೋಟೋಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ',
    awaitingDesc: 'ರೋಗ ಪತ್ತೆಹಚ್ಚಲು ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',

    googleKnowledgeBanner: 'ಗೂಗಲ್ ನಾಲೆಡ್ಜ್ ಬೇಸ್‌ನಿಂದ ಮಾಹಿತಿ ಹುಡುಕಿ',
    googleSearchBtn: 'ಗೂಗಲ್ ಸರ್ಚ್‌ನಲ್ಲಿ ನೋಡಿ',
    youtubeVideoHeader: 'ಯುಟ್ಯೂಬ್ ಪರಿಹಾರ ವೀಡಿಯೊ ಮಾರ್ಗದರ್ಶನ',
    watchVideoBtn: 'ಯುಟ್ಯೂಬ್‌ನಲ್ಲಿ ಚಿಕಿತ್ಸಾ ವೀಡಿಯೊ ವೀಕ್ಷಿಸಿ'
  },
  ml: {
    brandName: 'കിസാൻ-AI',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    cropRec: 'വിള ശുപാർശ',
    diseaseDetect: 'രോഗനിർണയം',
    advisory: 'AI കാർഷിക ഉപദേശം',
    schemes: 'സർക്കാർ പദ്ധതികൾ',
    welcomeFarmer: 'സ്വാഗതം, കർഷക മിത്രമേ!',
    weatherOverview: 'തത്സമയ കാലാവസ്ഥാ പ്രവചനം',
    soilType: 'മണ്ണിന്റെ തരം',
    farmSize: 'കൃഷിഭൂമി (ഏക്കർ)',
    location: 'സ്ഥലം / സംസ്ഥാനം',
    getRecommendation: 'ശുപാർശ നേടുക',
    analyzePlant: 'ഇല പരിശോധിക്കുക',
    generateAdvisory: 'ഉപദേശം നേടുക',
    matchGovtSchemes: 'അർഹമായ പദ്ധതികൾ',
    logout: 'ലോഗ് ഔട്ട്',
    login: 'ലോഗിൻ',
    signup: 'സൈൻ അപ്പ്',
    quickTools: 'വേഗത്തിലുള്ള കാർഷിക ഉപകരണങ്ങൾ',
    aiMatching: 'AI മാച്ചിംഗ്',
    instantScanner: 'ഇൻസ്റ്റന്റ് സ്‌കാനർ',
    bilingualTag: 'ബഹുഭാഷാ AI',
    subsidiesTag: '₹ സബ്‌സിഡികൾ',
    cropRecDesc: 'കൂടുതൽ വിളവ് നൽകുന്ന വിളകൾ കണ്ടെത്തുന്നതിന് മണ്ണിന്റെ NPK, pH, കാലാവസ്ഥ എന്നിവ കണക്കാക്കുക.',
    diseaseDesc: 'രോഗനിർണയത്തിനും ജൈവ/രാസ ചികിത്സകൾക്കുമായി ഇലയുടെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക.',
    advisoryDesc: 'നനയ്ക്കൽ സമയക്രമവും വളപ്രയോഗവും സംബന്ധിച്ച പ്രതിദിന AI ഉപദേശം നേടുക.',
    schemesDesc: 'പിഎം-കിസാൻ, ഫസൽ ബീമ, കെസിസി പദ്ധതികളുടെ അർഹത പരിശോധിക്കുക.',
    selectState: 'സംസ്ഥാനം / കേന്ദ്രഭരണ പ്രദേശം തിരഞ്ഞെടുക്കുക',
    annualIncome: 'വാർഷിക കുടുംബ വരുമാനം (₹)',
    calculateBtn: 'മികച്ച വിളകൾ കണ്ടെത്തുക',
    scanningBtn: 'പരിശോധിക്കുന്നു...',
    recalculateBtn: 'വീണ്ടും പരിശോധിക്കുക',
    eligible: 'അർഹതയുണ്ട്',
    notEligible: 'അർഹതയില്ല',
    reqDocs: 'ആവശ്യമായ രേഖകൾ',
    applyPortal: 'ഔദ്യോഗിക പോർട്ടലിൽ അപേക്ഷിക്കുക',

    selectUploadTitle: 'വിള തിരഞ്ഞെടുത്ത് ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
    targetCrop: 'വിള തിരഞ്ഞെടുക്കുക',
    clickDropBox: 'ഫോട്ടോ തിരഞ്ഞെടുക്കാൻ ഇവിടെ ക്ലിക്ക് ചെയ്യുക',
    supportsText: 'JPG, PNG, WEBP സപ്പോർട്ട് ചെയ്യും (പരമാവധി 10MB)',
    changePhoto: 'ഫോട്ടോ മാറ്റുക',
    removePhoto: 'ഫോട്ടോ മാറ്റുക',
    scanDiagnoseBtn: 'രോഗനിർണയം നടത്തുക',
    scientificName: 'ശാസ്ത്രീയ നാമം',
    aiConfidence: 'AI കൃത്യത',
    severityLevel: 'ഗുരുതരത',
    symptomsTitle: 'കണ്ടെത്തിയ രോഗലക്ഷണങ്ങൾ',
    organicRemedy: 'ജൈവ ചികിത്സ',
    chemicalRemedy: 'രാസ കീടനാശിനി പ്രയോഗം',
    preventiveCare: 'മുൻകരുതലുകൾ',
    nearbyMandisTitle: 'സമീപത്തെ കൃഷി കേന്ദ്രങ്ങൾ',
    awaitingInput: 'ഇലയുടെ ഫോട്ടോയ്ക്കായി കാത്തിരിക്കുന്നു',
    awaitingDesc: 'രോഗനിർണയത്തിനായി ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക.',

    googleKnowledgeBanner: 'ഗൂഗിൾ നോളജ് ബേസിൽ നിന്ന് വിവരങ്ങൾ കാണുക',
    googleSearchBtn: 'ഗൂഗിൾ സെർച്ചിൽ കാണുക',
    youtubeVideoHeader: 'യൂട്യൂബ് പരിഹാര വീഡിയോ',
    watchVideoBtn: 'യൂട്യൂബിൽ ചികിത്സാ വീഡിയോ കാണുക'
  },
  pa: {
    brandName: 'ਕਿਸਾਨ-AI',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    cropRec: 'ਫ਼ਸਲ ਦੀ ਸਿਫ਼ਾਰਸ਼',
    diseaseDetect: 'ਬੀਮਾਰੀ ਦੀ ਪਛਾਣ',
    advisory: 'AI ਖੇਤੀਬਾੜੀ ਸਲਾਹ',
    schemes: 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ',
    welcomeFarmer: 'ਜੀ ਆਇਆਂ ਨੂੰ, ਕਿਸਾਨ ਵੀਰੋ!',
    weatherOverview: 'ਲਾਈਵ ਮੌਸਮ ਦਾ ਹਾਲ',
    soilType: 'ਮਿੱਟੀ ਦੀ ਕਿਸਮ',
    farmSize: 'ਖੇਤ ਦਾ ਆਕਾਰ (ਏਕੜ)',
    location: 'ਸਥਾਨ / ਰਾਜ',
    getRecommendation: 'ਸਿਫ਼ਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ',
    analyzePlant: 'ਪੱਤੇ ਦੀ ਜਾਂਚ ਕਰੋ',
    generateAdvisory: 'ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ',
    matchGovtSchemes: 'ਯੋਗ ਸਕੀਮਾਂ ਵੇਖੋ',
    logout: 'ਲਾਗ ਆਊਟ',
    login: 'ਲਾਗਇਨ',
    signup: 'ਸਾਈਨ ਅੱਪ',
    quickTools: 'ਤੁਰੰਤ ਖੇਤੀ ਸੰਦ',
    aiMatching: 'AI ਮੈਚਿੰਗ',
    instantScanner: 'ਤੁਰੰਤ ਸਕੈਨਰ',
    bilingualTag: 'ਬਹੁ-ਭਾਸ਼ਾਈ AI',
    subsidiesTag: '₹ ਸਬਸਿਡੀਆਂ',
    cropRecDesc: 'ਵੱਧ ਝਾੜ ਦੇਣ ਵਾਲੀਆਂ ਫ਼ਸਲਾਂ ਲੱਭਣ ਲਈ ਮਿੱਟੀ ਦੇ NPK, pH ਅਤੇ ਮੌਸਮ ਦੀ ਗਣਨਾ ਕਰੋ।',
    diseaseDesc: 'ਬੀਮਾਰੀਆਂ ਦੀ ਪਛਾਣ ਅਤੇ ਜੈਵਿਕ/ਰਸਾਇਣਕ ਇਲਾਜ ਲਈ ਪੱਤੇ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ।',
    advisoryDesc: 'ਸਿੰਚਾਈ ਅਤੇ ਖਾਦਾਂ ਦੀ ਖੁਰਾਕ ਬਾਰੇ ਰੋਜ਼ਾਨਾ AI ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ।',
    schemesDesc: 'ਪੀਐਮ-ਕਿਸਾਨ, ਫ਼ਸਲ ਬੀਮਾ ਅਤੇ ਕੇਸੀਸੀ ਸਕੀਮਾਂ ਦੀ ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰੋ।',
    selectState: 'ਰਾਜ / ਕੇਂਦਰ ਸ਼ਾਸਿਤ ਪ੍ਰਦੇਸ਼ ਚੁਣੋ',
    annualIncome: 'ਸਾਲਾਨਾ ਪਰਿਵਾਰਕ ਆਮਦਨ (₹)',
    calculateBtn: 'ਸਭ ਤੋਂ ਵਧੀਆ ਫ਼ਸਲਾਂ ਲੱਭੋ',
    scanningBtn: 'ਜਾਂਚ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
    recalculateBtn: 'ਦੁਬਾਰਾ ਜਾਂਚ ਕਰੋ',
    eligible: 'ਯੋਗ',
    notEligible: 'ਅਯੋਗ',
    reqDocs: 'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼',
    applyPortal: 'ਅਧਿਕਾਰਤ ਪੋਰਟਲ \'ਤੇ ਅਪਲਾਈ ਕਰੋ',

    selectUploadTitle: 'ਫ਼ਸਲ ਚੁਣੋ ਅਤੇ ਪੱਤੇ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
    targetCrop: 'ਫ਼ਸਲ ਦੀ ਚੋਣ',
    clickDropBox: 'ਫੋਟੋ ਚੁਣਨ ਲਈ ਇੱਥੇ ਕਲਿੱਕ ਕਰੋ',
    supportsText: 'JPG, PNG, WEBP (ਵੱਧ ਤੋਂ ਵੱਧ 10MB)',
    changePhoto: 'ਫੋਟੋ ਬਦਲੋ',
    removePhoto: 'ਫੋਟੋ ਹਟਾਓ',
    scanDiagnoseBtn: 'ਬੀਮਾਰੀ ਦੀ ਜਾਂਚ ਕਰੋ',
    scientificName: 'ਵਿਗਿਆਨਕ ਨਾਂ',
    aiConfidence: 'AI ਸਟੀਕਤਾ',
    severityLevel: 'ਗੰਭੀਰਤਾ ਦਾ ਪੱਧਰ',
    symptomsTitle: 'ਦੇਖੇ ਗਏ ਲੱਛਣ',
    organicRemedy: 'ਜੈਵਿਕ ਇਲਾਜ',
    chemicalRemedy: 'ਰਸਾਇਣਕ ਛਿੜਕਾਅ',
    preventiveCare: 'ਬਚਾਅ ਦੇ ਉਪਾਅ',
    nearbyMandisTitle: 'ਨੇੜਲੇ ਖੇਤੀਬਾੜੀ ਕੇਂਦਰ',
    awaitingInput: 'ਪੱਤੇ ਦੀ ਫੋਟੋ ਦੀ ਉਡੀਕ ਹੈ',
    awaitingDesc: 'ਬੀਮਾਰੀ ਦੀ ਜਾਂਚ ਲਈ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ।',

    googleKnowledgeBanner: 'ਗੂਗਲ ਨੌਲੇਜ ਬੇਸ ਤੋਂ ਜਾਣਕਾਰੀ ਲੱਭੋ',
    googleSearchBtn: 'ਗੂਗਲ ਖੋਜ \'ਤੇ ਵੇਖੋ',
    youtubeVideoHeader: 'ਯੂਟਿਊਬ ਇਲਾਜ ਵੀਡੀਓ ਗਾਈਡ',
    watchVideoBtn: 'ਯੂਟਿਊਬ \'ਤੇ ਇਲਾਜ ਵੀਡੀਓ ਵੇਖੋ'
  },
  or: {
    brandName: 'କିଷାନ-AI',
    dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    cropRec: 'ଫସଲ ସୁପାରିଶ',
    diseaseDetect: 'ରୋଗ ଚିହ୍ନଟ',
    advisory: 'AI କୃଷି ପରାମର୍ଶ',
    schemes: 'ସରକାରୀ ଯୋଜନା',
    welcomeFarmer: 'ସ୍ବାଗତ, କୃଷକ ଭାଇ!',
    weatherOverview: 'ଲାଇଭ୍ ପାଣିପାଗ ପୂର୍ବାନୁମାନ',
    soilType: 'ମାଟିର ପ୍ରକାର',
    farmSize: 'ଜମିର ପରିମାଣ (ଏକର)',
    location: 'ସ୍ଥାନ / ରାଜ୍ୟ',
    getRecommendation: 'ସୁପାରିଶ ପାଆନ୍ତୁ',
    analyzePlant: 'ପତ୍ର ପରୀକ୍ଷା କରନ୍ତୁ',
    generateAdvisory: 'ପରାମର୍ଶ ପାଆନ୍ତୁ',
    matchGovtSchemes: 'ଯୋଗ୍ୟ ଯୋଜନା ଦେଖନ୍ତୁ',
    logout: 'ଲଗ୍ ଆଉଟ୍',
    login: 'ଲଗଇନ୍',
    signup: 'ସାଇନ୍ ଅପ୍',
    quickTools: 'ଦ୍ରୁତ କୃଷି ଉପକରଣ',
    aiMatching: 'AI ମ୍ୟାଚିଂ',
    instantScanner: 'ଇନଷ୍ଟାଣ୍ଟ ସ୍କାନର୍',
    bilingualTag: 'ବହୁଭାଷୀ AI',
    subsidiesTag: '₹ ସବସିଡି',
    cropRecDesc: 'ଅଧିକ ଅମଳକ୍ଷମ ଫସଲ ଖୋଜିବା ପାଇଁ ମାଟିର NPK, pH ଏବଂ ପାଣିପାଗ ଗଣନା କରନ୍ତୁ।',
    diseaseDesc: 'ରୋଗ ନିରୂପଣ ଏବଂ ଜୈବିକ/ରାସାୟନିକ ଚିକିତ୍ସା ପାଇଁ ପତ୍ରର ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ।',
    advisoryDesc: 'ଜଳସେଚନ ସମୟସୂଚୀ ଏବଂ ଖତ ପ୍ରୟୋଗ ବିଷୟରେ ଦୈନନ୍ଦିନ AI ପରାମର୍ଶ ପାଆନ୍ତୁ।',
    schemesDesc: 'ପିଏମ୍-କିଷାନ, ଫସଲ ବୀମା ଏବଂ କେସିସି ଯୋଜନାର ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରନ୍ତୁ।',
    selectState: 'ରାଜ୍ୟ / କେନ୍ଦ୍ରଶାସିତ ଅଞ୍ଚଳ ଚୟନ କରନ୍ତୁ',
    annualIncome: 'ବାର୍ଷିକ ପାରିବାରିକ ଆୟ (₹)',
    calculateBtn: 'ଉତ୍ତମ ଫସଲ ଖୋଜନ୍ତୁ',
    scanningBtn: 'ସ୍କାନିଂ ଚାଲିଛି...',
    recalculateBtn: 'ପୁନର୍ବାର ଯାଞ୍ଚ କରନ୍ତୁ',
    eligible: 'ଯୋଗ୍ୟ',
    notEligible: 'ଅଯୋଗ୍ୟ',
    reqDocs: 'ଆବଶ୍ୟକ କାଗଜପତ୍ର',
    applyPortal: 'ଅଫିସିଆଲ୍ ପୋର୍ଟାଲରେ ଆବେଦନ କରନ୍ତୁ',

    selectUploadTitle: 'ଫସଲ ଚୟନ କରନ୍ତୁ ଏବଂ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ',
    targetCrop: 'ଫସଲ ଚୟନ',
    clickDropBox: 'ଫଟୋ ଚୟନ କରିବା ପାଇଁ ଏଠାରେ କ୍ଲିକ୍ କରନ୍ତୁ',
    supportsText: 'JPG, PNG, WEBP (ସର୍ବାଧିକ 10MB)',
    changePhoto: 'ଫଟୋ ବଦଳାନ୍ତୁ',
    removePhoto: 'ଫଟୋ ହଟାନ୍ତୁ',
    scanDiagnoseBtn: 'ରୋଗ ଚିହ୍ନଟ କରନ୍ତୁ',
    scientificName: 'ବୈଜ୍ଞାନିକ ନାମ',
    aiConfidence: 'AI ସଠିକତା ହାର',
    severityLevel: 'ଗାମ୍ଭୀର୍ଯ୍ୟ',
    symptomsTitle: 'ଦେଖାଯାଇଥିବା ଲକ୍ଷଣ',
    organicRemedy: 'ଜୈବିକ ଚିକିତ୍ସା',
    chemicalRemedy: 'ରାସାୟନିକ ସ୍ପ୍ରେ ପଦ୍ଧତି',
    preventiveCare: 'ପ୍ରତିଷେଧକ ବ୍ୟବସ୍ଥା',
    nearbyMandisTitle: 'ନିକଟସ୍ଥ କୃଷି ସେବା କେନ୍ଦ୍ର',
    awaitingInput: 'ପତ୍ର ଫଟୋ ପାଇଁ ଅପେକ୍ଷା କରାଯାଇଛି',
    awaitingDesc: 'ରୋଗ ଚିହ୍ନଟ ପାଇଁ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ।',

    googleKnowledgeBanner: 'ଗୁଗଲ ନଲେଜ୍ ବେସରୁ ସୂଚନା ସନ୍ଧାନ କରନ୍ତୁ',
    googleSearchBtn: 'ଗୁଗଲ ସର୍ଚ୍ଚରେ ଦେଖନ୍ତୁ',
    youtubeVideoHeader: 'ୟୁଟ୍ୟୁବ୍ ସମାଧାନ ଭିଡିଓ',
    watchVideoBtn: 'ୟୁଟ୍ୟୁବରେ ଚିକିତ୍ସା ଭିଡିଓ ଦେଖନ୍ତୁ'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('kisan_lang') || 'en');

  const changeLanguage = (newLangCode) => {
    setLang(newLangCode);
    localStorage.setItem('kisan_lang', newLangCode);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  const getCropName = (cropKey) => {
    const key = (cropKey || 'wheat').toLowerCase();
    return CROPS_LOCALIZED[key]?.[lang] || CROPS_LOCALIZED[key]?.['en'] || cropKey;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t, getCropName, supportedLanguages: SUPPORTED_LANGUAGES, indianStates: INDIAN_STATES, cropsLocalized: CROPS_LOCALIZED }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
